steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_DOCKER_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGE}', '.']

images:
- ${_DOCKER_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGE}

logsBucket: 'gs://${_CLOUDBUILD_LOGS_BUCKET}'
options:
  logging: GCS_ONLY
