steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_DOCKER_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGE}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_DOCKER_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGE}']

logsBucket: 'gs://cloud-build-storage-bucket-eu'
options:
  logging: GCS_ONLY
